import { SiteFooter, SiteNav } from "../site-nav";

const projects = [
  { number:"01", kind:"Independent product build", status:"Active development · Cross-platform alpha", title:"RepQuest", lead:"A privacy-first sports learning game that adapts the playbook to each player’s age, experience, and progress.", description:"A 23-sport learning platform for responsive web and mobile that combines guided beginner playbooks, real short-form game clips, sport and position pathways, interactive challenges, and meaningful progression.", ownership:"I own the product strategy, requirements, experience architecture, content and data modeling, privacy design, and hands-on implementation across React, TypeScript, Expo, and React Native. I use an AI-assisted development workflow, then validate the result through code review, automated checks, and TestFlight releases.", challenge:"Teach the complexity of sports across ages and experience levels without reducing learning to generic trivia—or collecting unnecessary information from younger players.", approach:"Designed a reusable React and TypeScript content model and game engine with adaptive remediation, concept-level mastery, XP, streaks, badges, and age-aware pacing; added real-game media and beginner guidance; unified the experience with an Expo and React Native mobile companion; and designed Cloudflare D1-backed account, parental-consent, privacy-event, progress-sync, and safe-league architecture.", evidence:["End-to-end cross-platform product execution","Reusable 23-sport learning architecture","Privacy and parental-consent system design","Adaptive learning, mastery, and gamification"], tools:["React","TypeScript","Expo","React Native","Cloudflare D1","API design","Privacy-first architecture"], links:[{ href:"https://testflight.apple.com/join/FTBqt973", label:"Try the beta on TestFlight", primary:true },{ href:"https://github.com/ammorgan/sports-iq/blob/main/docs/REPQUEST_PRD.md", label:"Read the product requirements" },{ href:"https://github.com/ammorgan/sports-iq", label:"View the source repository" }] },
  { number:"02", kind:"Independent product concept", status:"Active development · Functional alpha", title:"AI Quality Intelligence", lead:"Release intelligence designed around explainability, traceability, and human judgment.", description:"A local-first product concept exploring how engineering teams can make faster, more confident software release decisions with explainable automation and responsible AI.", challenge:"Reduce repetitive quality-assurance effort without turning consequential release decisions into a black box.", approach:"Built a privacy-conscious React and TypeScript alpha with deterministic analysis at its core and an extensible provider architecture for future AI capabilities.", evidence:["Strongly typed application design","Explainable risk modeling","Automated verification","Enterprise-minded product strategy"], tools:["React","TypeScript","System design","Responsible AI","Automated testing"], link:null },
  { number:"03", kind:"Personal technical project", status:"Concept exploration", title:"Engineering Analytics Platform", lead:"Multi-repository activity translated into operational intelligence for engineering leaders.", description:"A React-based platform concept designed to analyze activity across multiple GitLab repositories and make delivery health, development activity, defect trends, and status insights easier to see.", challenge:"Give engineering leaders a coherent view of delivery signals spread across multiple repositories.", approach:"Explored GitLab API integrations, caching strategies, data persistence, and AI-assisted analysis to convert repository activity into operational reporting.", evidence:["Cross-repository analysis","Delivery-health reporting","Caching and persistence strategy","AI-assisted insight generation"], tools:["React","GitLab APIs","Data persistence","Caching","AI analysis"], link:null },
  { number:"04", kind:"Enterprise knowledge initiative", status:"Delivered enterprise initiative", title:"Engineering Knowledge Platform", lead:"Searchable documentation that reduced tribal knowledge and improved onboarding.", description:"An engineering documentation modernization initiative built with MkDocs and automated delivery practices.", challenge:"Critical technical knowledge was difficult to discover, creating friction for onboarding and day-to-day delivery.", approach:"Built a searchable MkDocs platform with CI/CD deployment and led the migration of technical requirements from Agility to GitLab.", evidence:["Searchable knowledge architecture","Automated documentation delivery","Standardized technical requirements","Improved portfolio visibility"], tools:["MkDocs","GitLab","CI/CD","Information architecture","Documentation"], link:null },
];

export default function Projects() {
  return <main id="top"><SiteNav />
    <header className="pageHero shell projectsHero"><span className="eyebrow">Selected technical work</span><h1>Systems thinking, <em>made tangible.</em></h1><p>Projects that show how I connect product judgment, technical depth, responsible AI, and operational outcomes.</p><small>Public artifacts are linked where they can be shared responsibly.</small></header>
    <section className="projectList shell">{projects.map(project=><article className="projectCase" key={project.number}>
      <div className="projectMeta"><span className="projectNumber">{project.number}</span><span>{project.kind}</span>{project.status && <b>{project.status}</b>}</div>
      <div className="projectTitle"><h2>{project.title}</h2><p>{project.lead}</p></div>
      <p className="projectDescription">{project.description}</p>
      {project.ownership && <div className="projectOwnership"><span>My ownership</span><p>{project.ownership}</p></div>}
      <div className="caseGrid"><div><span>Challenge</span><p>{project.challenge}</p></div><div><span>Approach</span><p>{project.approach}</p></div></div>
      <div className="evidenceBlock"><span className="eyebrow">What it demonstrates</span><div>{project.evidence.map(item=><p key={item}>{item}</p>)}</div></div>
      <div className="tagRow">{project.tools.map(tool=><span key={tool}>{tool}</span>)}</div>
      {project.links && <div className="projectActions">{project.links.map(link=><a className={link.primary ? "primaryButton" : "projectArtifactLink"} href={link.href} target="_blank" rel="noreferrer" aria-label={`${link.label} (opens in a new tab)`} key={link.href}>{link.label} <span>↗</span></a>)}</div>}
    </article>)}</section>
    <section className="toolkit"><div className="shell"><div className="sectionHeading lightHeading"><span className="eyebrow">Technical toolkit</span><h2>Fluent across the <em>delivery system.</em></h2></div><div className="toolkitGrid"><div><h3>Discovery</h3><p>Problem framing · Repository analysis · Requirements discovery · Systems mapping</p></div><div><h3>Product &amp; design</h3><p>Roadmaps · Backlog strategy · Figma / XD partnership · Accessibility · Privacy-aware experiences</p></div><div><h3>Engineering delivery</h3><p>React · TypeScript · Expo · React Native · APIs · Cloudflare D1 · Data modeling · GitLab · CI/CD · AWS · MkDocs</p></div><div><h3>AI &amp; analysis</h3><p>GitHub Copilot · LLM workflows · Deterministic analysis · Responsible AI</p></div></div></div></section>
    <SiteFooter />
  </main>;
}
